### PR TITLE
added snippets

### PR DESCRIPTION
**Pull request by MarieLataretu**
Hey there, I just added two snippets:
- module inclusion
- workflow definition

### CODE REVIEW

**Comment by pditommaso** [comment]
Here there's a conflict to fix to get it merged

**Comment by pditommaso** [comment]
@jemunro can you please review this to verify is still valid?

**Comment by jemunro** [comment]
This looks to be redundant now as workflow and include snippets have already been added.

https://github.com/nextflow-io/vscode-language-nextflow/blob/077b217b43dd423f3628ddd2b3ec8aea0a64dcd1/snippets/snippets.json#L28-L50

https://github.com/nextflow-io/vscode-language-nextflow/blob/077b217b43dd423f3628ddd2b3ec8aea0a64dcd1/snippets/snippets.json#L56-L60

**Comment by pditommaso** [comment]
Ok, thanks

**Pull request closed without merging**
